<?php
$title = "Autenticação no sistema";

$this->headTitle($title);
?>



<div class="container">

  <div id="loginbox" style="margin-top:100px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info" >
      <div class="panel-heading">
        <div class="panel-title">Login</div>
      </div>

      <div style="padding-top:30px" class="panel-body" >

        <div id="login-alert" class="col-sm-12">

          <?php if ($this->error): ?>
            <p><b>Usuário ou senha inválidos</b></p>
          <?php endif; ?>

          <?php if ($this->cadastro): ?>
            <p><b>Usuário ou senha inválidos</b></p>
          <?php endif; ?>

        </div>

        <?php echo $this->form()->openTag($form)?>

        <div style="margin-bottom: 25px" class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
          <?php echo $this->formElement($form->get('email'))?>
          <?php echo $this->formElementErrors($form->get('email'))?>
        </div>

        <div style="margin-bottom: 25px" class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
          <?php echo $this->formElement($form->get('senha'))?>
          <?php echo $this->formElementErrors($form->get('senha'))?>
        </div>



        <!--    <div class="input-group">
                    <!--  <div class="checkbox">
                        <label>
                          <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
                        </label>
                      </div>
                    </div> -->


        <div style="margin-top:10px" class="form-group">
          <!-- Button -->

          <div class="col-sm-12 controls">
            <input class="btn btn-success" type="submit" value="Login">
            <a id="btn-fblogin" href="<?php echo $this->url('agenda-user',array('controller' => 'users', 'action' => 'new')); ?>" class="btn btn-primary">Criar uma conta</a>

          </div>
        </div>


        <div class="form-group">
          <div class="col-md-12 control">

          </div>
        </div>
        <?php echo $this->form()->closeTag($form)?>



      </div>
    </div>
  </div>

</div>

</div>