<h1>Novo usuario</h1>

<br/>

<?php

$form = $this->form;

$form->setAttribute('action', $this->url('agenda-admin', array('controller' => 'users', 'action' => 'new')));

$form->prepare();
echo $this->form()->openTag($form);
?>

<div class="panel panel-info">
    <div class="panel-heading">Formulario de cadastro</div>
    <div class="panel-body">

        <div id="login-alert" class="col-sm-12">

            <?php if ($this->message): ?>
                <p><b>Email já cadastrado!</b></p>
            <?php endif; ?>

        </div>


        <div class="form-group">
            <?php
            echo $this->formHidden($form->get('id'));
            ?>
        </div>
        <div class="form-group">
            <?php
            echo $this->formRow($form->get('nome'));
            ?>
        </div>
        <div class="form-group">
            <?php
            echo $this->formRow($form->get('email'));
            ?>
        </div>
        <div class="form-group">
            <?php
            echo $this->formRow($form->get('senha'));
            ?>
        </div>
        <div class="form-group">
            <?php
            echo $this->formSubmit($form->get('submit'));
            ?>
            <a class="btn btn-danger" href="<?php echo $this->url('agenda-auth') ?>">Cancelar</a>
        </div>
        <?php
        echo $this->form()->closeTag($form);
        ?>
    </div>
</div>